main:
- name: Home
  url: /
  weight: 10
- name: This Week
  url: /planner/
  weight: 12
- name: What's New
  url: /whatsnew/
  weight: 15
- name: Posts
  url: /blog/
  weight: 20
- name: Gallery
  url: /gallery/
  weight: 25
- name: Wiki
  url: https://github.com/norton120/svdefiant/wiki
  weight: 30
- name: Refit Plan
  url: https://github.com/users/norton120/projects/4
  weight: 40
- name: About
  url: /about/
  weight: 50
