############################
## Author
############################

author:
  name: "S/V Defiant"
  image: author.jpeg
  greeting: "Refitting, restoring, and sailing <i>Defiant</i>, a 1989 Bayfield 36 Cutter :sailboat:"
  icon: ":anchor:"

###############################
## OpenGraph & Twitter Cards
###############################

title: "S/V Defiant"
description: "Build log and voyage journal for Sailing Vessel Defiant"
images:
  - thumbnail.jpeg
